<div class="text-center">
    <h1>
        ACCOUNT
    </h1>
    Change account information in database.

</div>
<div class="text-center">
    <form action="" method="POST">
        <?php
            //echo $_SESSION['managedUser'];
            $managing = false;
            if ($_SESSION['managedUser']['LOGIN'] != $_SESSION['user']['LOGIN']) {
                //echo "uprava nekoho jinyho";
                $managing = true;
            }
        ?>
        <div class="form-group text-center">
            <label for="exampleInputLogin">Your Name</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputLogin" placeholder="Enter your full name" name="fullName"
                   value="<?php
                   if ($managing)
                   {
                       echo $_SESSION['managedUser']['FULL_NAME'];
                   }
                   else
                   {
                       echo $_SESSION['user']['FULL_NAME'];
                   }
                   ?>">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputEmail1">E-mail address</label>
            <input type="email" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email"
                   value="<?= $_SESSION['user']['EMAIL'] ?>">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group text-center">
            <label for="exampleInputLogin">Login</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputLogin" placeholder="Enter login" name="login"
                   value="<?= $_SESSION['user']['LOGIN'] ?>">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputPassword1">Old Password</label>
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="Old Password" name="oldPassword">
        </div>
        <div class="form-group text-center">
            <label for="exampleInputPassword1">New Password</label>
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="New Password" name="password">
        </div>
        <div class="form-group text-center">
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="New Password (agian)" name="passwordCheck">
            <small id="passwordHelp" class="form-text text-muted">Never share your password with anyone else.</small>
        </div>
        <button type="submit" name="update"
                class="btn col-lg-2 col-md-4 col-sm-6 btn-dark">Update</button>
    </form>
</div>