<div class="text-center">
    <h1>
        Articles
    </h1>
    Here you can browse accepted articles. Signed users can see other categories.
    <div class="p-3 mb-2 bg-dark text-white"></div>
</div>
<div class="text-center">
    <div class="accordion" id="accordionExample">
        <?php
        /**
         * Only for signed users
         */
        if ($_SESSION['signed'])
        {
        ?>
        <!--MY ARTICLES-->
        <div class="card">
            <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                    <button class="btn btn-dark col-lg-2 col-md-3 col-sm-6" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        My Articles
                    </button>
                </h2>
            </div>
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">File Name</th>
                            <th scope="col">Abstract</th>
                            <th scope="col">State</th>
                            <th scope="col">Reviews</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $this->tableOfMyArticles();
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php
            /**
             * Only for admins
             */
            if ($_SESSION['user']['ROLE'] == "ADMIN" )
            {
        ?>
        <!-- ARTICLES UNDER REVIEW-->
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h2 class="mb-0">
                    <button class="btn btn-dark col-lg-2 col-md-3 col-sm-6 collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                       Articles in review
                    </button>
                </h2>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">File Name</th>
                            <th scope="col">Abstract</th>
                            <th scope="col">State</th>
                            <th scope="col">Reviews</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $this->tableOfArticlesUnderReview();
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php
            }
            /**
             * Only for admins and reviewers
             */
            if ( $_SESSION['user']['ROLE'] == "REVIEWER" || $_SESSION['user']['ROLE'] == "ADMIN" )
            {
                /**
                 * If I have some articles assigned
                 */
                if ($_SESSION['areReviews'])
                {
        ?>
                    <!-- ARTICLES FOR ME TO REVIEW-->
                    <div class="card">
                        <div class="card-header" id="headingThree">
                            <h2 class="mb-0">
                                <button class="btn btn-dark col-lg-2 col-md-3 col-sm-6 collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Assigned articles
                                </button>
                            </h2>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                            <div class="card-body table-responsive">
                                <table class="table table-striped">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">Title</th>
                                        <th scope="col">File Name</th>
                                        <th scope="col">Abstract</th>
                                        <th scope="col">State</th>
                                        <th scope="col">Reviews</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    $this->tableOfArticlesMyReview();
                                    ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

        <?php
                    /**
                     * End of only for admins and reviewers
                     */
                    }
                /**
                 * End of only for admins
                 */
                }
            /**
             * End of for signed users
             */
            }
        ?>
        <!-- ALL ACCEPTED ARTICLES-->
        <div class="card">
            <div class="card-header" id="headingFour">
                <h2 class="mb-0">
                    <button class="btn btn-dark col-lg-2 col-md-3 col-sm-6 collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                        Accepted articles
                    </button>
                </h2>
            </div>
            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                <div class="card-body table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">File Name</th>
                            <th scope="col">Abstract</th>
                            <th scope="col">Reviews</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $this->tableOfArticlesAccepted();
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>