<div class="text-center">
    <h1>
        Assignment
    </h1>
</div>
<?php
//echo $_SESSION['assignArticle']['TITLE'];

?>
<div class="text-center">
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="form-group text-center">
            <label for="exampleInputTitle">Title</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-secondary"
                   id="exampleInputTitle" placeholder="Enter title of an article" name="title"
                   value="<?=$_SESSION['assignArticle']['TITLE']?>" disabled>

        </div>
        <div class="form-group text-center">
            <label for="exampleInputFile">PDF document</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-secondary"
                   id="exampleInputFile" name="file" accept="application/pdf"
                   value="<?=$_SESSION['assignArticle']['FILE_NAME']?>" disabled>
        </div>
        <div class="form-group text-center">
            <label for="exampleInputAbstract">Abstract</label>
            <textarea type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-secondary"
                      id="exampleInputAbstract" placeholder="Enter abstract" name="abstract"
                      disabled><?=$_SESSION['assignArticle']['ABSTRACT']?></textarea>
        </div>
        <div class="form-group text-center">
            <label for="exampleInputReviewer">Reviewer</label><br>
            <select class="custom-select form-control col-lg-2 col-md-3 col-sm-4 btn-dark bg-dark" name="reviewer">
                <option value="" disabled selected>Select reviewer</option>
                <?php

                    $this->allReviewers();
                ?>

            </select>
        </div>
        <button type="submit" name="assign"
                class="btn col-lg-2 col-md-3 col-sm-4 btn-dark">Assign</button>
    </form>
</div>
