<div class="text-center">
    <h1>
        Editor
    </h1>
    Creating or modifying articles.
    <div class="p-3 mb-2 bg-dark text-white"></div>
</div>
<div class="text-center">
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="form-group text-center">
            <label for="exampleInputTitle">Title</label>
            <input type="text" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2
            <?php if ($_SESSION['editing']) echo "btn-secondary"; else echo "btn-dark";?>"
                   id="exampleInputTitle" placeholder="Enter title of an article" name="title"
                <?php
                if ($_SESSION['editing'])
                    echo "value=\"". $_SESSION['editedArticle']['TITLE'] ."\" disabled";
                ?>>

        </div>
        <?php
        if (!$_SESSION['editing'])
        {
        ?>
        <div class="form-group text-center">
            <label for="exampleInputFile">PDF document</label>
            <input type="file" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 btn-dark"
                   id="exampleInputFile" name="file" accept="application/pdf">
        </div>
        <?php
        }
        ?>
        <div class="form-group text-center">
            <label for="exampleInputAbstract">Abstract</label>
            <textarea type="text" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 btn-dark"
                      id="exampleInputAbstract" placeholder="Enter abstract" name="abstract"><?php if ($_SESSION['editing']) echo $_SESSION['editedArticle']['ABSTRACT'];?></textarea>
        </div>

        <button type="submit" name="delete"
                class="btn col-lg-2 col-md-3 col-sm-4 btn-danger" <?php if (!$_SESSION['editing']) echo "disabled"; ?>>Delete</button>
        <?php
        if (!$_SESSION['editing'])
        {
        ?>
        <button type="submit" name="create"
                class="btn col-lg-2 col-md-3 col-sm-4 btn-dark">Create</button>
        <?php
        }
        else
        {
        ?>
            <button type="submit" name="update"
                    class="btn col-lg-2 col-md-3 col-sm-4 btn-dark">Update</button>
        <?php
        }
        ?>

    </form>
</div>