<div class="text-center">
    <h1>
        EDITOR
    </h1>
    VISIOTR -can't see
    AUTHOR - open old article to edit
            - or create new one
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="form-group text-center">
            <label for="exampleInputTitle">Title</label>
            <input type="text" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 btn-dark"
                   id="exampleInputTitle" placeholder="Enter title of an article" name="title">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputFile">PDF document</label>
            <input type="file" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 btn-dark"
                   id="exampleInputFile" name="file" accept="application/pdf">
        </div>
        <div class="form-group text-center">
            <label for="exampleInputAbstract">Abstract</label>
            <textarea type="text" class="form-control col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2 btn-dark"
                      id="exampleInputAbstract" placeholder="Enter abstract" name="abstract"></textarea>
        </div>

        <button type="submit" name="delete"
                class="btn col-lg-2 col-md-3 col-sm-4 btn-danger" disabled>Delete</button>
        <button type="submit" name="save"
                class="btn col-lg-2 col-md-3 col-sm-4 btn-dark">Save</button>
    </form>
</div>