<div class="text-center">
    <h1>
        Info
    </h1>
    <div class="p-3 mb-2 bg-dark text-white"></div>
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Et harum quidem rerum facilis est et expedita
        distinctio. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Etiam neque. Fusce suscipit libero
        eget elit. Vivamus porttitor turpis ac leo. Proin mattis lacinia justo. Praesent in mauris eu tortor porttitor
        accumsan. Curabitur sagittis hendrerit ante. Nam sed tellus id magna elementum tincidunt. Nullam dapibus
        fermentum ipsum. Integer malesuada. In rutrum. Nullam sit amet magna in magna gravida vehicula. Pellentesque
        pretium lectus id turpis. Nam quis nulla. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,
        consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam
        quaerat voluptatem.</p>

    <p>Praesent id justo in neque elementum ultrices. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis
        vel sapien. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias
        consequatur aut perferendis doloribus asperiores repellat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
        qui officia deserunt mollit anim id est laborum. Nulla non lectus sed nisl molestie malesuada. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Cras pede libero,
        dapibus nec, pretium sit amet, tempor quis. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Nam
        libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat
        facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Praesent vitae arcu tempor neque
        lacinia pretium. Maecenas lorem.</p>

    <p>Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nemo enim ipsam voluptatem quia voluptas sit
        aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
        Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus.
        Praesent id justo in neque elementum ultrices. Curabitur bibendum justo non orci. Duis pulvinar. Etiam
        bibendum elit eget erat. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Maecenas libero.
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea
        commodi consequatur? Quisque tincidunt scelerisque libero. Aliquam erat volutpat. Cras pede libero, dapibus nec,
        pretium sit amet, tempor quis. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe
        eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Etiam egestas wisi a erat. Morbi leo mi,
        nonummy eget tristique non, rhoncus non leo.</p>

    <p>Vivamus porttitor turpis ac leo. Integer pellentesque quam vel velit. Ut enim ad minima veniam, quis nostrum
        exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Sed convallis
        magna eu sem. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias
        consequatur aut perferendis doloribus asperiores repellat. In rutrum. Etiam dictum tincidunt diam. Nulla
        accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Aliquam in
        lorem sit amet leo accumsan lacinia. Sed convallis magna eu sem. Nulla pulvinar eleifend sem. In sem justo,
        commodo ut, suscipit at, pharetra vitae, orci. Pellentesque habitant morbi tristique senectus et netus et
        malesuada fames ac turpis egestas.</p>

    <p>Maecenas aliquet accumsan leo. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. In sem
        justo, commodo ut, suscipit at, pharetra vitae, orci. Aenean id metus id velit ullamcorper pulvinar. Vivamus
        porttitor turpis ac leo. Mauris dictum facilisis augue. Nemo enim ipsam voluptatem quia voluptas sit aspernatur
        aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Duis
        condimentum augue id magna semper rutrum. Nullam rhoncus aliquam metus. Donec iaculis gravida nulla. Cras
        elementum. Fusce suscipit libero eget elit. Nam sed tellus id magna elementum tincidunt. Et harum quidem rerum
        facilis est et expedita distinctio. Aenean id metus id velit ullamcorper pulvinar.</p>
</div>