<div class="text-center">
    <form action="" method="POST">
        <div class="form-group text-center">
            <label for="exampleInputLogin">Login</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputLogin" placeholder="Enter login" name="login">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="Password" name="password">
            <small id="passwordHelp" class="form-text text-muted">Never share your password with anyone else.</small>
        </div>
        <button type="submit" name="signin"
                class="btn col-lg-2 col-md-4 col-sm-6 btn-dark">Login</button>
    </form>
</div>