<div class="text-center">
    <h1>
        Registration
    </h1>
    <div class="p-3 mb-2 bg-dark text-white"></div>
</div>
<div class="text-center">
    <form action="" method="POST">
        <div class="form-group text-center">
            <label for="exampleInputLogin">Your Name</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputLogin" placeholder="Enter your full name" name="fullName">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputEmail1">E-mail address</label>
            <input type="email" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group text-center">
            <label for="exampleInputLogin">Login</label>
            <input type="text" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputLogin" placeholder="Enter login" name="login">

        </div>
        <div class="form-group text-center">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="Password" name="password">
        </div>
        <div class="form-group text-center">
            <input type="password" class="form-control col-lg-2 offset-lg-5 col-md-4 offset-md-4 col-sm-6 offset-sm-3 btn-dark"
                   id="exampleInputPassword1" placeholder="Password (agian)" name="passwordCheck">
            <small id="passwordHelp" class="form-text text-muted">Never share your password with anyone else.</small>
        </div>
        <button type="submit" name="signup"
                class="btn col-lg-2 col-md-4 col-sm-6 btn-dark">Register</button>
    </form>
</div>